//
// Copyright (c) 2026-Present ScorpionC2 public-person "Lucas de Moraes Claro" and all anonymous contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
// 

/*
 * After using any BOLD color, needs to use RESET to remove BOLD mod
 * Same thing to ITALIC colors
 */

#pragma once

#define _PREFIX "\x1b["
#define _END "m"
#define _MOD_FG "38;2;"
#define _MOD_BG "48;2;"
#define _MOD_ITALIC "3;"
#define _MOD_BOLD "1;"

#define RESET _PREFIX "0" _END

#define C_GREEN_BASE "72;168;48"
#define C_GREEN_LIGHT "105;200;83"
#define C_GREEN_DARK "37;137;0"

#define BG_GREEN _PREFIX _MOD_BG C_GREEN_BASE _END
#define BG_GREEN_DARK _PREFIX _MOD_BG C_GREEN_DARK _END
#define BG_GREEN_LIGHT _PREFIX _MOD_BG C_GREEN_LIGHT _END
#define FG_GREEN _PREFIX _MOD_FG C_GREEN_BASE _END
#define FG_GREEN_DARK _PREFIX _MOD_FG C_GREEN_DARK _END
#define FG_GREEN_LIGHT _PREFIX _MOD_FG C_GREEN_LIGHT _END
#define FG_GREEN_BOLD _PREFIX _MOD_BOLD _MOD_FG C_GREEN_BASE _END
#define FG_GREEN_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_GREEN_DARK _END
#define FG_GREEN_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_GREEN_LIGHT _END
#define FG_GREEN_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_GREEN_BASE _END
#define FG_GREEN_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_GREEN_DARK _END
#define FG_GREEN_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_GREEN_LIGHT _END
#define FG_GREEN_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_GREEN_BASE _END
#define FG_GREEN_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_GREEN_DARK _END
#define FG_GREEN_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_GREEN_LIGHT _END

#define C_RED_BASE "187;6;30"
#define C_RED_LIGHT "222;59;61"
#define C_RED_DARK "145;0;6"

#define BG_RED _PREFIX _MOD_BG C_RED_BASE _END
#define BG_RED_DARK _PREFIX _MOD_BG C_RED_DARK _END
#define BG_RED_LIGHT _PREFIX _MOD_BG C_RED_LIGHT _END
#define FG_RED _PREFIX _MOD_FG C_RED_BASE _END
#define FG_RED_DARK _PREFIX _MOD_FG C_RED_DARK _END
#define FG_RED_LIGHT _PREFIX _MOD_FG C_RED_LIGHT _END
#define FG_RED_BOLD _PREFIX _MOD_BOLD _MOD_FG C_RED_BASE _END
#define FG_RED_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_RED_DARK _END
#define FG_RED_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_RED_LIGHT _END
#define FG_RED_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_RED_BASE _END
#define FG_RED_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_RED_DARK _END
#define FG_RED_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_RED_LIGHT _END
#define FG_RED_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_RED_BASE _END
#define FG_RED_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_RED_DARK _END
#define FG_RED_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_RED_LIGHT _END

#define C_MAGENTA_BASE "211;0;108"
#define C_MAGENTA_LIGHT "248;45;137"
#define C_MAGENTA_DARK "163;0;81"

#define BG_MAGENTA _PREFIX _MOD_BG C_MAGENTA_BASE _END
#define BG_MAGENTA_DARK _PREFIX _MOD_BG C_MAGENTA_DARK _END
#define BG_MAGENTA_LIGHT _PREFIX _MOD_BG C_MAGENTA_LIGHT _END
#define FG_MAGENTA _PREFIX _MOD_FG C_MAGENTA_BASE _END
#define FG_MAGENTA_DARK _PREFIX _MOD_FG C_MAGENTA_DARK _END
#define FG_MAGENTA_LIGHT _PREFIX _MOD_FG C_MAGENTA_LIGHT _END
#define FG_MAGENTA_BOLD _PREFIX _MOD_BOLD _MOD_FG C_MAGENTA_BASE _END
#define FG_MAGENTA_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_MAGENTA_DARK _END
#define FG_MAGENTA_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_MAGENTA_LIGHT _END
#define FG_MAGENTA_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_MAGENTA_BASE _END
#define FG_MAGENTA_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_MAGENTA_DARK _END
#define FG_MAGENTA_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_MAGENTA_LIGHT _END
#define FG_MAGENTA_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_MAGENTA_BASE _END
#define FG_MAGENTA_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_MAGENTA_DARK _END
#define FG_MAGENTA_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_MAGENTA_LIGHT _END

#define C_YELLOW_BASE "252;213;7"
#define C_YELLOW_LIGHT "255;249;168"
#define C_YELLOW_DARK "219;180;0"

#define BG_YELLOW _PREFIX _MOD_BG C_YELLOW_BASE _END
#define BG_YELLOW_DARK _PREFIX _MOD_BG C_YELLOW_DARK _END
#define BG_YELLOW_LIGHT _PREFIX _MOD_BG C_YELLOW_LIGHT _END
#define FG_YELLOW _PREFIX _MOD_FG C_YELLOW_BASE _END
#define FG_YELLOW_DARK _PREFIX _MOD_FG C_YELLOW_DARK _END
#define FG_YELLOW_LIGHT _PREFIX _MOD_FG C_YELLOW_LIGHT _END
#define FG_YELLOW_BOLD _PREFIX _MOD_BOLD _MOD_FG C_YELLOW_BASE _END
#define FG_YELLOW_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_YELLOW_DARK _END
#define FG_YELLOW_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_YELLOW_LIGHT _END
#define FG_YELLOW_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_YELLOW_BASE _END
#define FG_YELLOW_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_YELLOW_DARK _END
#define FG_YELLOW_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_YELLOW_LIGHT _END
#define FG_YELLOW_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_YELLOW_BASE _END
#define FG_YELLOW_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_YELLOW_DARK _END
#define FG_YELLOW_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_YELLOW_LIGHT _END

#define C_BLUE_BASE "0;129;244"
#define C_BLUE_LIGHT "34;162;255"
#define C_BLUE_DARK "0;99;195"

#define BG_BLUE _PREFIX _MOD_BG C_BLUE_BASE _END
#define BG_BLUE_DARK _PREFIX _MOD_BG C_BLUE_DARK _END
#define BG_BLUE_LIGHT _PREFIX _MOD_BG C_BLUE_LIGHT _END
#define FG_BLUE _PREFIX _MOD_FG C_BLUE_BASE _END
#define FG_BLUE_DARK _PREFIX _MOD_FG C_BLUE_DARK _END
#define FG_BLUE_LIGHT _PREFIX _MOD_FG C_BLUE_LIGHT _END
#define FG_BLUE_BOLD _PREFIX _MOD_BOLD _MOD_FG C_BLUE_BASE _END
#define FG_BLUE_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_BLUE_DARK _END
#define FG_BLUE_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_BLUE_LIGHT _END
#define FG_BLUE_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_BLUE_BASE _END
#define FG_BLUE_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_BLUE_DARK _END
#define FG_BLUE_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_BLUE_LIGHT _END
#define FG_BLUE_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_BLUE_BASE _END
#define FG_BLUE_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_BLUE_DARK _END
#define FG_BLUE_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_BLUE_LIGHT _END

#define C_CYAN_BASE "0;236;248"
#define C_CYAN_LIGHT "140;255;255"
#define C_CYAN_DARK "0;201;210"

#define BG_CYAN _PREFIX _MOD_BG C_CYAN_BASE _END
#define BG_CYAN_DARK _PREFIX _MOD_BG C_CYAN_DARK _END
#define BG_CYAN_LIGHT _PREFIX _MOD_BG C_CYAN_LIGHT _END
#define FG_CYAN _PREFIX _MOD_FG C_CYAN_BASE _END
#define FG_CYAN_DARK _PREFIX _MOD_FG C_CYAN_DARK _END
#define FG_CYAN_LIGHT _PREFIX _MOD_FG C_CYAN_LIGHT _END
#define FG_CYAN_BOLD _PREFIX _MOD_BOLD _MOD_FG C_CYAN_BASE _END
#define FG_CYAN_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_CYAN_DARK _END
#define FG_CYAN_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_CYAN_LIGHT _END
#define FG_CYAN_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_CYAN_BASE _END
#define FG_CYAN_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_CYAN_DARK _END
#define FG_CYAN_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_CYAN_LIGHT _END
#define FG_CYAN_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_CYAN_BASE _END
#define FG_CYAN_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_CYAN_DARK _END
#define FG_CYAN_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_CYAN_LIGHT _END

#define C_WHITE_BASE "255;255;255"

#define BG_WHITE _PREFIX _MOD_BG C_WHITE_BASE _END
#define FG_WHITE _PREFIX _MOD_FG C_WHITE_BASE _END
#define FG_WHITE_BOLD _PREFIX _MOD_BOLD _MOD_FG C_WHITE_BASE _END
#define FG_WHITE_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_WHITE_BASE _END
#define FG_WHITE_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_WHITE_BASE _END

#define C_BLACK_BASE "0;0;0"

#define BG_BLACK _PREFIX _MOD_BG C_BLACK_BASE _END
#define FG_BLACK _PREFIX _MOD_FG C_BLACK_BASE _END
#define FG_BLACK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_BLACK_BASE _END
#define FG_BLACK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_BLACK_BASE _END
#define FG_BLACK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_BLACK_BASE _END

#define C_PINK_BASE "248;0;198"
#define C_PINK_LIGHT "255;97;220"
#define C_PINK_DARK "200;0;159"

#define BG_PINK _PREFIX _MOD_BG C_PINK_BASE _END
#define BG_PINK_DARK _PREFIX _MOD_BG C_PINK_DARK _END
#define BG_PINK_LIGHT _PREFIX _MOD_BG C_PINK_LIGHT _END
#define FG_PINK _PREFIX _MOD_FG C_PINK_BASE _END
#define FG_PINK_DARK _PREFIX _MOD_FG C_PINK_DARK _END
#define FG_PINK_LIGHT _PREFIX _MOD_FG C_PINK_LIGHT _END
#define FG_PINK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_PINK_BASE _END
#define FG_PINK_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_PINK_DARK _END
#define FG_PINK_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_PINK_LIGHT _END
#define FG_PINK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_PINK_BASE _END
#define FG_PINK_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_PINK_DARK _END
#define FG_PINK_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_PINK_LIGHT _END
#define FG_PINK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_PINK_BASE _END
#define FG_PINK_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_PINK_DARK _END
#define FG_PINK_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_PINK_LIGHT _END

#define C_PURPLE_BASE "126;28;216"
#define C_PURPLE_LIGHT "155;72;251"
#define C_PURPLE_DARK "96;0;175"

#define BG_PURPLE _PREFIX _MOD_BG C_PURPLE_BASE _END
#define BG_PURPLE_DARK _PREFIX _MOD_BG C_PURPLE_DARK _END
#define BG_PURPLE_LIGHT _PREFIX _MOD_BG C_PURPLE_LIGHT _END
#define FG_PURPLE _PREFIX _MOD_FG C_PURPLE_BASE _END
#define FG_PURPLE_DARK _PREFIX _MOD_FG C_PURPLE_DARK _END
#define FG_PURPLE_LIGHT _PREFIX _MOD_FG C_PURPLE_LIGHT _END
#define FG_PURPLE_BOLD _PREFIX _MOD_BOLD _MOD_FG C_PURPLE_BASE _END
#define FG_PURPLE_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_PURPLE_DARK _END
#define FG_PURPLE_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_PURPLE_LIGHT _END
#define FG_PURPLE_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_PURPLE_BASE _END
#define FG_PURPLE_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_PURPLE_DARK _END
#define FG_PURPLE_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_PURPLE_LIGHT _END
#define FG_PURPLE_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_PURPLE_BASE _END
#define FG_PURPLE_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_PURPLE_DARK _END
#define FG_PURPLE_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_PURPLE_LIGHT _END

#define C_ORANGE_BASE "255;107;0"
#define C_ORANGE_LIGHT "255;158;93"
#define C_ORANGE_DARK "209;84;0"

#define BG_ORANGE _PREFIX _MOD_BG C_ORANGE_BASE _END
#define BG_ORANGE_DARK _PREFIX _MOD_BG C_ORANGE_DARK _END
#define BG_ORANGE_LIGHT _PREFIX _MOD_BG C_ORANGE_LIGHT _END
#define FG_ORANGE _PREFIX _MOD_FG C_ORANGE_BASE _END
#define FG_ORANGE_DARK _PREFIX _MOD_FG C_ORANGE_DARK _END
#define FG_ORANGE_LIGHT _PREFIX _MOD_FG C_ORANGE_LIGHT _END
#define FG_ORANGE_BOLD _PREFIX _MOD_BOLD _MOD_FG C_ORANGE_BASE _END
#define FG_ORANGE_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_ORANGE_DARK _END
#define FG_ORANGE_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_ORANGE_LIGHT _END
#define FG_ORANGE_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_ORANGE_BASE _END
#define FG_ORANGE_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_ORANGE_DARK _END
#define FG_ORANGE_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_ORANGE_LIGHT _END
#define FG_ORANGE_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_ORANGE_BASE _END
#define FG_ORANGE_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_ORANGE_DARK _END
#define FG_ORANGE_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_ORANGE_LIGHT _END

#define C_GREY_BASE "99;99;99"
#define C_GREY_LIGHT "143;143;143"
#define C_GREY_DARK "58;58;58"

#define BG_GREY _PREFIX _MOD_BG C_GREY_BASE _END
#define BG_GREY_DARK _PREFIX _MOD_BG C_GREY_DARK _END
#define BG_GREY_LIGHT _PREFIX _MOD_BG C_GREY_LIGHT _END
#define FG_GREY _PREFIX _MOD_FG C_GREY_BASE _END
#define FG_GREY_DARK _PREFIX _MOD_FG C_GREY_DARK _END
#define FG_GREY_LIGHT _PREFIX _MOD_FG C_GREY_LIGHT _END
#define FG_GREY_BOLD _PREFIX _MOD_BOLD _MOD_FG C_GREY_BASE _END
#define FG_GREY_DARK_BOLD _PREFIX _MOD_BOLD _MOD_FG C_GREY_DARK _END
#define FG_GREY_LIGHT_BOLD _PREFIX _MOD_BOLD _MOD_FG C_GREY_LIGHT _END
#define FG_GREY_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_GREY_BASE _END
#define FG_GREY_DARK_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_GREY_DARK _END
#define FG_GREY_LIGHT_ITALIC _PREFIX _MOD_ITALIC _MOD_FG C_GREY_LIGHT _END
#define FG_GREY_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_GREY_BASE _END
#define FG_GREY_DARK_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_GREY_DARK _END
#define FG_GREY_LIGHT_BOLD_ITALIC _PREFIX _MOD_BOLD _MOD_ITALIC _MOD_FG C_GREY_LIGHT _END